// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // ── 1. Getting Started ────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'For Agents',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Agents' }],
        },
        {
          type: 'category',
          label: 'For Administrators',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Administrators' }],
        },
        {
          type: 'category',
          label: 'For Supervisors & QA Leads',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Supervisors_and_QA_Leads' }],
        },
        {
          type: 'category',
          label: 'For Hosting Partners',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Hosting_Partners' }],
        },
        {
          type: 'category',
          label: 'For Conversation Designers',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Conversation_Designers' }],
        },
        {
          type: 'category',
          label: 'For Developers & Integrators',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Developers_and_Integrators' }],
        },
      ],
    },

    // ── 2. Platform Overview ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Platform Overview',
      items: [{ type: 'autogenerated', dirName: 'cx/Platform_Overview' }],
    },

    // ── 3. Capabilities ───────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Capabilities',
      items: [
        {
          type: 'category',
          label: 'Digital Channels',
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Digital_Channels' }],
        },
        {
          type: 'category',
          label: 'Voice & Video',
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Voice_and_Video' }],
        },
        {
          type: 'category',
          label: 'Reporting & Analytics',
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Reporting_and_Analytics' }],
        },
        {
          type: 'category',
          label: 'Security & Compliance',
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Security_and_Compliance' }],
        },
        {
          type: 'category',
          label: 'Workforce Management',
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Workforce_Management' }],
        },
      ],
    },

    // ── 4. How-to Guides ──────────────────────────────────────────────────
    {
      type: 'category',
      label: 'How-to Guides',
      items: [
        {
          type: 'category',
          label: 'Agent',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Agent' }],
        },
        {
          type: 'category',
          label: 'Administrator',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Administrator' }],
        },
        {
          type: 'category',
          label: 'Supervisor & QA Lead',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Supervisor_and_QA_Lead' }],
        },
        {
          type: 'category',
          label: 'Conversation Designer / AI Specialist',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Conversation_Designer' }],
        },
        {
          type: 'category',
          label: 'Developer / Integrator',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Developer_Integrator' }],
        },
        {
          type: 'category',
          label: 'Hosting Partner',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Hosting_Partner' }],
        },
        {
          type: 'category',
          label: 'Platform Operator',
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Platform_Operator' }],
        },
      ],
    },

    // ── 5. Reference ──────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Schemas & Data Model',
          items: [
            {
              type: 'category',
              label: 'CIM Message Schema',
              items: [{ type: 'autogenerated', dirName: 'cx/Reference/Schemas_and_Data_Model/CIM_Message_Schema' }],
            },
            {
              type: 'category',
              label: 'Socket Events',
              items: [{ type: 'autogenerated', dirName: 'cx/Reference/Schemas_and_Data_Model/Socket_Events' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Glossary',
          items: [{ type: 'autogenerated', dirName: 'cx/Reference/Glossary' }],
        },
      ],
    },
  ],
};

export default sidebars;
