// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // ── 1. Getting Started ────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: { type: 'doc', id: 'cx/Getting_Started/index' },
      items: [
        'cx/Getting_Started/For_Agents/Agent-Quick-Start-Guide',
        {
          type: 'category',
          label: 'For Administrators',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Administrators' }],
        },
        {
          type: 'category',
          label: 'For Supervisors & QA Leads',
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Supervisors_and_QA_Leads' }],
        },
        {
          type: 'category',
          label: 'For Partners & Resellers',
          link: { type: 'doc', id: 'cx/Getting_Started/For_Hosting_Partners/Hosting-Partner-Quick-Start' },
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Hosting_Partners' }],
        },
        {
          type: 'category',
          label: 'For Conversation Designers',
          link: { type: 'doc', id: 'cx/Getting_Started/For_Conversation_Designers/Conversation-Designer-Quick-Start' },
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Conversation_Designers' }],
        },
        {
          type: 'category',
          label: 'For Developers & Integrators',
          link: { type: 'doc', id: 'cx/Getting_Started/For_Developers_and_Integrators/Developer-and-Integrator-Quick-Start' },
          items: [{ type: 'autogenerated', dirName: 'cx/Getting_Started/For_Developers_and_Integrators' }],
        },
      ],
    },

    // ── 2. Platform Overview ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Platform Overview',
      link: { type: 'doc', id: 'cx/Platform_Overview/Expertflow-CX-Platform-Overview' },
      items: [{ type: 'autogenerated', dirName: 'cx/Platform_Overview' }],
    },

    // ── 3. Capabilities ───────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Capabilities',
      items: [
        {
          type: 'category',
          label: 'Digital Channels',
          link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/index' },
          items: [
            // ── Features (shared across channels) ────────────────────────────
            {
              type: 'category',
              label: 'Features',
              link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/Channel-Features' },
              items: [
                'cx/Capabilities/Digital_Channels/Conversation-View',
                'cx/Capabilities/Digital_Channels/Consult-Transfer-Conference',
                'cx/Capabilities/Digital_Channels/Agent-Hand-Raise',
                'cx/Capabilities/Digital_Channels/Browser-and-Sound-Notifications',
                'cx/Capabilities/Digital_Channels/Customer-Labels',
                'cx/Capabilities/Digital_Channels/Customer-Advanced-Filters',
                'cx/Capabilities/Digital_Channels/Business-Calendars',
                'cx/Capabilities/Digital_Channels/Business-Calendars-Limitations',
              ],
            },
            // ── Chat & Messaging ─────────────────────────────────────────────
            {
              type: 'category',
              label: 'Chat & Messaging',
              items: [
                'cx/Capabilities/Digital_Channels/Customer-Widget-Features-Capabilities',
                'cx/Capabilities/Digital_Channels/Customer-Widget-Embedding-Guide',
                {
                  type: 'category',
                  label: 'WhatsApp',
                  link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/WhatsApp/index' },
                  items: [
                    'cx/Capabilities/Digital_Channels/WhatsApp/WhatsApp-Cloud-API',
                    'cx/Capabilities/Digital_Channels/WhatsApp/360dialog-WhatsApp-Overview',
                  ],
                },
                'cx/Capabilities/Digital_Channels/Telegram-Channel-Overview',
                'cx/Capabilities/Digital_Channels/Telegram-Bot-Creation-Guide',
                'cx/Capabilities/Digital_Channels/Telegram-Configuration-Guide',
                'cx/Capabilities/Digital_Channels/Telegram-Media-Types',
                'cx/Capabilities/Digital_Channels/Telegram-Connector-Limitations',
                'cx/Capabilities/Digital_Channels/SMPP-Channel-Overview',
                'cx/Capabilities/Digital_Channels/SMPP-Configuration-Guide',
              ],
            },
            // ── Social Media ─────────────────────────────────────────────────
            {
              type: 'category',
              label: 'Social Media',
              items: [
                'cx/Capabilities/Digital_Channels/Facebook-Channel-Overview',
                'cx/Capabilities/Digital_Channels/Facebook-Configuration-Guide',
                'cx/Capabilities/Digital_Channels/Facebook-Connector-Limitations',
                'cx/Capabilities/Digital_Channels/Twitter-Channel-Overview',
                'cx/Capabilities/Digital_Channels/Twitter-Configuration-Guide',
                'cx/Capabilities/Digital_Channels/LinkedIn-Channel-Overview',
                'cx/Capabilities/Digital_Channels/LinkedIn-Account-Onboarding',
                'cx/Capabilities/Digital_Channels/LinkedIn-Configuration-Guide',
                'cx/Capabilities/Digital_Channels/LinkedIn-Dev-Connector-Deployment',
                'cx/Capabilities/Digital_Channels/YouTube-Channel-Overview',
                'cx/Capabilities/Digital_Channels/Google-Play-Store-Channel-Overview',
                'cx/Capabilities/Digital_Channels/Google-Play-Store-Account-Onboarding',
                'cx/Capabilities/Digital_Channels/Google-Play-Store-Configuration-Guide',
                'cx/Capabilities/Digital_Channels/Google-Play-Store-FAQs-and-Troubleshooting',
              ],
            },
            // ── Email ─────────────────────────────────────────────────────────
            {
              type: 'category',
              label: 'Email',
              items: [
                'cx/Capabilities/Digital_Channels/Email-Channel-Overview',
                'cx/Capabilities/Digital_Channels/Email-Configuration-IMAP-SMTP',
                'cx/Capabilities/Digital_Channels/Email-Configuration-MS-Exchange',
                'cx/Capabilities/Digital_Channels/Email-Limitations',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Voice & Video',
          link: { type: 'doc', id: 'cx/Capabilities/Voice_and_Video/Voice-and-Video-Overview' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Voice_and_Video' }],
        },
        {
          type: 'category',
          label: 'Reporting & Analytics',
          link: { type: 'doc', id: 'cx/Capabilities/Reporting_and_Analytics/Reports-and-Analytics' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Reporting_and_Analytics' }],
        },
        {
          type: 'category',
          label: 'Security & Compliance',
          link: { type: 'doc', id: 'cx/Capabilities/Security_and_Compliance/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Security_and_Compliance' }],
        },
        {
          type: 'category',
          label: 'Workforce Management',
          link: { type: 'doc', id: 'cx/Capabilities/Workforce_Management/Workforce-Management-Overview' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Workforce_Management' }],
        },
      ],
    },

    // ── 4. How-to Guides ──────────────────────────────────────────────────
    {
      type: 'category',
      label: 'How-to Guides',
      items: [
        {
          type: 'category',
          label: 'Agent',
          link: { type: 'doc', id: 'cx/How-to_Guides/Agent/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Agent' }],
        },
        {
          type: 'category',
          label: 'Administrator',
          link: { type: 'doc', id: 'cx/How-to_Guides/Administrator/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Administrator' }],
        },
        {
          type: 'category',
          label: 'Supervisor & QA Lead',
          link: { type: 'doc', id: 'cx/How-to_Guides/Supervisor_and_QA_Lead/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Supervisor_and_QA_Lead' }],
        },
        {
          type: 'category',
          label: 'Conversation Designer / AI Specialist',
          link: { type: 'doc', id: 'cx/How-to_Guides/Conversation_Designer/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Conversation_Designer' }],
        },
        {
          type: 'category',
          label: 'Developer / Integrator',
          link: { type: 'doc', id: 'cx/How-to_Guides/Developer_Integrator/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Developer_Integrator' }],
        },
        {
          type: 'category',
          label: 'Hosting Partner',
          link: { type: 'doc', id: 'cx/How-to_Guides/Hosting_Partner/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Hosting_Partner' }],
        },
        {
          type: 'category',
          label: 'Reseller Partner',
          link: { type: 'doc', id: 'cx/How-to_Guides/Reseller_Partner/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Reseller_Partner' }],
        },
      ],
    },

    // ── 5. Reference ──────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Schemas & Data Model',
          items: [
            {
              type: 'category',
              label: 'CIM Message Schema',
              link: { type: 'doc', id: 'cx/Reference/Schemas_and_Data_Model/CIM_Message_Schema/CIM-Messages' },
              items: [{ type: 'autogenerated', dirName: 'cx/Reference/Schemas_and_Data_Model/CIM_Message_Schema' }],
            },
            {
              type: 'category',
              label: 'Socket Events',
              link: { type: 'doc', id: 'cx/Reference/Schemas_and_Data_Model/Socket_Events/index' },
              items: [{ type: 'autogenerated', dirName: 'cx/Reference/Schemas_and_Data_Model/Socket_Events' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Glossary',
          items: [{ type: 'autogenerated', dirName: 'cx/Reference/Glossary' }],
        },
      ],
    },
  ],
};

export default sidebars;
