// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // ── 1. Getting Started ────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: { type: 'doc', id: 'cx/Getting_Started/index' },
      items: [
        { type: 'doc', id: 'cx/Getting_Started/For_Agents/index', label: 'For Agents' },
        { type: 'doc', id: 'cx/Getting_Started/For_Administrators/index', label: 'For Administrators' },
        { type: 'doc', id: 'cx/Getting_Started/For_Supervisors_and_QA_Leads/index', label: 'For Supervisors & QA Leads' },
        {
          type: 'category',
          label: 'For Platform Operators',
          link: { type: 'doc', id: 'cx/Getting_Started/For_Platform_Operators/index' },
          items: [
            { type: 'doc', id: 'cx/Getting_Started/For_Platform_Operators/Installation-Guide', label: 'Installation Guide' },
            { type: 'doc', id: 'cx/Getting_Started/For_Platform_Operators/Upgrade-Guide', label: 'Upgrade Guide' },
          ],
        },
        { type: 'doc', id: 'cx/Getting_Started/For_Partners/index', label: 'For Partners' },
        { type: 'doc', id: 'cx/Getting_Started/For_Conversation_Designers/index', label: 'For Conversation Designers' },
        { type: 'doc', id: 'cx/Getting_Started/For_Developers_and_Integrators/index', label: 'For Developers & Integrators' },
      ],
    },

    // ── 2. Solutions ──────────────────────────────────────────────────────
    // Business-outcome overviews for pre-sales and evaluation audiences.
    // Placed near the top because Solutions speak to business value before
    // platform details — the natural entry point for evaluators.
    {
      type: 'category',
      label: 'Solutions',
      link: { type: 'doc', id: 'cx/Solutions/index' },
      items: [
        // index.md of each sub-folder is used as the category link (above).
        // It must NOT appear again as a child item — use explicit item lists,
        // never autogenerated, when the folder's index.md is the category link.
        { type: 'doc', id: 'cx/Solutions/Campaign_Manager/index', label: 'Campaign Manager' },
        {
          type: 'category',
          label: 'Surveys',
          link: { type: 'doc', id: 'cx/Solutions/Surveys/index' },
          items: [
            { type: 'doc', id: 'cx/Solutions/Surveys/Survey-Campaigns', label: 'Survey Campaigns' },
            { type: 'doc', id: 'cx/Solutions/Surveys/Post-Collaboration-Surveys', label: 'Post-Collaboration Surveys' },
          ],
        },
        { type: 'doc', id: 'cx/Solutions/Workforce_Management/index', label: 'Workforce Management' },
        { type: 'doc', id: 'cx/Solutions/Quality_Management/index', label: 'Quality Management' },
      ],
    },

    // ── 3. Platform Overview ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Platform Overview',
      link: { type: 'doc', id: 'cx/Platform_Overview/index' },
      items: [
        'cx/Platform_Overview/Expertflow-CX-Platform-Overview',
        'cx/Platform_Overview/Platform-Architecture',
        'cx/Platform_Overview/AI-Self-Service-Capabilities',
        'cx/Platform_Overview/Customer-Journey-Orchestration',
        'cx/Platform_Overview/Security-and-Compliance-Whitepaper',
      ],
    },

    // ── 4. Capabilities ───────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Capabilities',
      link: { type: 'doc', id: 'cx/Capabilities/index' },
      items: [
        {
          type: 'category',
          label: 'Digital Channels',
          link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/index' },
          items: [
            // ── Chat & Messaging ─────────────────────────────────────────────
            {
              type: 'category',
              label: 'Chat & Messaging',
              items: [
                'cx/Capabilities/Digital_Channels/Customer-Widget-Features-Capabilities',
                {
                  type: 'category',
                  label: 'WhatsApp',
                  link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/WhatsApp/index' },
                  items: [
                    'cx/Capabilities/Digital_Channels/WhatsApp/WhatsApp-Cloud-API',
                    'cx/Capabilities/Digital_Channels/WhatsApp/360dialog-WhatsApp-Overview',
                  ],
                },
                {
                  type: 'category',
                  label: 'Telegram',
                  link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/Telegram/index' },
                  items: [
                    'cx/Capabilities/Digital_Channels/Telegram/Telegram-Bot-Creation-Guide',
                    'cx/Capabilities/Digital_Channels/Telegram/Telegram-Configuration-Guide',
                    'cx/Capabilities/Digital_Channels/Telegram/Telegram-Media-Types',
                    'cx/Capabilities/Digital_Channels/Telegram/Telegram-Connector-Limitations',
                  ],
                },
                {
                  type: 'category',
                  label: 'SMS',
                  link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/SMS/index' },
                  items: [],
                },
              ],
            },
            // ── Social Media ─────────────────────────────────────────────────
            {
              type: 'category',
              label: 'Social Media',
              items: [
                'cx/Capabilities/Digital_Channels/Facebook/index',
                'cx/Capabilities/Digital_Channels/Twitter/index',
                'cx/Capabilities/Digital_Channels/LinkedIn/index',
                'cx/Capabilities/Digital_Channels/YouTube/index',
                'cx/Capabilities/Digital_Channels/Google_Play_Store/index',
              ],
            },
            // ── Email ─────────────────────────────────────────────────────────
            {
              type: 'category',
              label: 'Email',
              items: [
                'cx/Capabilities/Digital_Channels/Email/index',
                'cx/Capabilities/Digital_Channels/Email-Configuration-IMAP-SMTP',
                'cx/Capabilities/Digital_Channels/Email-Configuration-MS-Exchange',
                'cx/Capabilities/Digital_Channels/Email-Limitations',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Voice & Video',
          link: { type: 'doc', id: 'cx/Capabilities/Voice_and_Video/Voice-and-Video-Overview' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Voice_and_Video' }],
        },
        {
          type: 'category',
          label: 'Reporting & Analytics',
          link: { type: 'doc', id: 'cx/Capabilities/Reporting_and_Analytics/Reports-and-Analytics' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Reporting_and_Analytics' }],
        },
        {
          type: 'category',
          label: 'Security & Compliance',
          link: { type: 'doc', id: 'cx/Capabilities/Security_and_Compliance/index' },
          items: [
            'cx/Capabilities/Security_and_Compliance/Audit-Logging',
            'cx/Capabilities/Security_and_Compliance/GDPR-Compliance',
            'cx/Capabilities/Security_and_Compliance/HIPAA-Compliance',
            'cx/Capabilities/Security_and_Compliance/PCI-DSS-Compliance',
            'cx/Capabilities/Security_and_Compliance/VRS-PCI-DSS-Compliance',
            'cx/Capabilities/Security_and_Compliance/Secure-OTP-Lifecycle-Compliance',
          ],
        },
        {
          type: 'category',
          label: 'Customer Management',
          link: { type: 'doc', id: 'cx/Capabilities/Customer_Management/index' },
          items: [
            'cx/Capabilities/Customer_Management/Customer-Labels',
            'cx/Capabilities/Customer_Management/Customer-Advanced-Filters',
          ],
        },
        {
          type: 'category',
          label: 'Business Calendars',
          link: { type: 'doc', id: 'cx/Capabilities/Digital_Channels/Business-Calendars' },
          items: [
            'cx/Capabilities/Digital_Channels/Business-Calendars-Limitations',
          ],
        },
        {
          type: 'category',
          label: 'Workforce Management',
          link: { type: 'doc', id: 'cx/Capabilities/Workforce_Management/Workforce-Management-Overview' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Workforce_Management' }],
        },
        {
          type: 'category',
          label: 'AI & Automation',
          link: { type: 'doc', id: 'cx/Capabilities/AI_and_Automation/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/AI_and_Automation' }],
        },
        {
          type: 'category',
          label: 'Quality Management',
          link: { type: 'doc', id: 'cx/Capabilities/Quality_Management/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Quality_Management' }],
        },
        {
          type: 'category',
          label: 'Routing & Queue Management',
          link: { type: 'doc', id: 'cx/Capabilities/Routing_and_Queue_Management/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Routing_and_Queue_Management' }],
        },
        {
          type: 'category',
          label: 'Integrations & Connectors',
          link: { type: 'doc', id: 'cx/Capabilities/Integrations_and_Connectors/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/Capabilities/Integrations_and_Connectors' }],
        },
        { type: 'doc', id: 'cx/Capabilities/Conversation-View', label: 'Conversation View' },
        { type: 'doc', id: 'cx/Capabilities/Conversation-Studio', label: 'Conversation Studio' },
      ],
    },

    // ── 5. How-to Guides ──────────────────────────────────────────────────
    {
      type: 'category',
      label: 'How-to Guides',
      link: { type: 'doc', id: 'cx/How-to_Guides/index' },
      items: [
        {
          type: 'category',
          label: 'Agent',
          link: { type: 'doc', id: 'cx/How-to_Guides/Agent/index' },
          items: [
            { type: 'autogenerated', dirName: 'cx/How-to_Guides/Agent' },
            'cx/Capabilities/Digital_Channels/Browser-and-Sound-Notifications',
          ],
        },
        {
          type: 'category',
          label: 'Administrator',
          link: { type: 'doc', id: 'cx/How-to_Guides/Administrator/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Administrator' }],
        },
        {
          type: 'category',
          label: 'Supervisor & QA Lead',
          link: { type: 'doc', id: 'cx/How-to_Guides/Supervisor_and_QA_Lead/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Supervisor_and_QA_Lead' }],
        },
        {
          type: 'category',
          label: 'Conversation Designer / AI Specialist',
          link: { type: 'doc', id: 'cx/How-to_Guides/Conversation_Designer/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Conversation_Designer' }],
        },
        {
          type: 'category',
          label: 'Developer / Integrator',
          link: { type: 'doc', id: 'cx/How-to_Guides/Developer_Integrator/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Developer_Integrator' }],
        },
        {
          type: 'category',
          label: 'Platform Operator',
          link: { type: 'doc', id: 'cx/How-to_Guides/Platform_Operator/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Platform_Operator' }],
        },
        {
          type: 'category',
          label: 'Partner',
          link: { type: 'doc', id: 'cx/How-to_Guides/Partner/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/How-to_Guides/Partner' }],
        },
      ],
    },

    // ── 6. Reference ──────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'doc', id: 'cx/Reference/index' },
      items: [
        { type: 'doc', id: 'cx/Reference/Release-Lifecycle-and-Versioning', label: 'Release Lifecycle & Versioning' },
        { type: 'doc', id: 'cx/Reference/WFM-Compatibility-Guide', label: 'WFM Compatibility Guide' },
        { type: 'doc', id: 'cx/Reference/Hybrid-Chat-to-CX-Migration-Comparison', label: 'Hybrid Chat to CX Migration Comparison' },
        { type: 'doc', id: 'cx/Reference/Dialer-Performance-Benchmarks', label: 'Dialer Performance Benchmarks' },
        { type: 'doc', id: 'cx/Reference/Facebook-Connector-Limitations', label: 'Facebook Connector Limitations' },
        { type: 'doc', id: 'cx/Reference/Google-Play-Store-FAQs-and-Troubleshooting', label: 'Google Play Store FAQs & Troubleshooting' },
        {
          type: 'category',
          label: 'Architecture & Infrastructure',
          link: { type: 'doc', id: 'cx/Reference/Architecture_and_Infrastructure/index' },
          items: [{ type: 'autogenerated', dirName: 'cx/Reference/Architecture_and_Infrastructure' }],
        },
        {
          type: 'category',
          label: 'API & SDK',
          link: { type: 'doc', id: 'cx/Reference/API_and_SDK/index' },
          items: [
            { type: 'doc', id: 'cx/Reference/API_and_SDK/Agent-Desk-Developer-Guide', label: 'AgentManager SDK Reference' },
          ],
        },
        {
          type: 'category',
          label: 'Schemas & Data Model',
          items: [
            {
              type: 'category',
              label: 'CIM Message Schema',
              link: { type: 'doc', id: 'cx/Reference/Schemas_and_Data_Model/CIM_Message_Schema/CIM-Messages' },
              items: [{ type: 'autogenerated', dirName: 'cx/Reference/Schemas_and_Data_Model/CIM_Message_Schema' }],
            },
            {
              type: 'category',
              label: 'Socket Events',
              link: { type: 'doc', id: 'cx/Reference/Schemas_and_Data_Model/Socket_Events/index' },
              items: [{ type: 'autogenerated', dirName: 'cx/Reference/Schemas_and_Data_Model/Socket_Events' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Glossary',
          link: { type: 'doc', id: 'cx/Reference/Glossary/Glossary-of-Key-Terms' },
          items: [{ type: 'autogenerated', dirName: 'cx/Reference/Glossary' }],
        },
      ],
    },
  ],
};

export default sidebars;
